<?xml version="1.0" encoding="UTF-8"?><testrun name="TestNotaDAOImpl" project="JDBC_Sistema_Secundario" tests="10" started="10" failures="1" errors="0" ignored="0">
  <testsuite name="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.623">
    <testcase name="testWeCanSeeAllMarksByStudentIdAndSubjectId" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.503"/>
    <testcase name="testWeCannotSeeAllMarksByStudentIdAndSubjectId" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.022">
      <failure>java.lang.AssertionError: Expected exception: ar.com.sistema.secundario.exceptions.EntityNotExistsException&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:34)&#13;
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)&#13;
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)&#13;
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)&#13;
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testWeCanDeleteAMark" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.014"/>
    <testcase name="testWeCannotDeleteAMark" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.009"/>
    <testcase name="testWeCanUpdateAMark" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.015"/>
    <testcase name="testWeCannotUpdateAMark" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.004"/>
    <testcase name="testWeCanInsertAMark" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.011"/>
    <testcase name="testWeCanSeeAllMarks" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.022"/>
    <testcase name="testWeCanSeeAnSpecificMarkById" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.01"/>
    <testcase name="testWeCannotSeeAnSpecificMarkById" classname="ar.com.sistema.secundario.test.TestNotaDAOImpl" time="0.01"/>
  </testsuite>
</testrun>
